// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM24XOW2RiLXbw2rL6Y8jVPMn_2MkN8cY',
    appId: '1:703733227981:android:036e0f76faf0e972dfe484',
    messagingSenderId: '703733227981',
    projectId: 'seaportal-9cca9',
    storageBucket: 'seaportal-9cca9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQiVECd2FgNDoP_vGd2kEeoJCFOVOZAZw',
    appId: '1:703733227981:ios:9047e9fb0eee4a0adfe484',
    messagingSenderId: '703733227981',
    projectId: 'seaportal-9cca9',
    storageBucket: 'seaportal-9cca9.appspot.com',
    iosBundleId: 'com.hapeye.autohouse',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRTei2XVWThwnn3QtYnTJov6T5Q-vID10',
    appId: '1:703733227981:web:398951c81951ec35dfe484',
    messagingSenderId: '703733227981',
    projectId: 'seaportal-9cca9',
    authDomain: 'seaportal-9cca9.firebaseapp.com',
    storageBucket: 'seaportal-9cca9.appspot.com',
    measurementId: 'G-KVYCK2DVH9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQiVECd2FgNDoP_vGd2kEeoJCFOVOZAZw',
    appId: '1:703733227981:ios:9047e9fb0eee4a0adfe484',
    messagingSenderId: '703733227981',
    projectId: 'seaportal-9cca9',
    storageBucket: 'seaportal-9cca9.appspot.com',
    iosBundleId: 'com.hapeye.autohouse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRTei2XVWThwnn3QtYnTJov6T5Q-vID10',
    appId: '1:703733227981:web:7315e327d5ac3530dfe484',
    messagingSenderId: '703733227981',
    projectId: 'seaportal-9cca9',
    authDomain: 'seaportal-9cca9.firebaseapp.com',
    storageBucket: 'seaportal-9cca9.appspot.com',
    measurementId: 'G-Z381T1PRQ0',
  );

}